### PR TITLE
fix: reinstate `har-validator`

### PR DESCRIPTION
**Pull request by grxy**
## PR Checklist:
- [ ] I have run `npm test` locally and all tests are passing. [they are passing in CI]
- [ ] I have added/updated tests for any new behavior. [N/A]
       
- [ ] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A]
       

## PR Description

Reinstates `har-validator`

Fixes https://github.com/cypress-io/cypress/issues/19097
Fixes https://github.com/cypress-io/request/issues/14

### CODE REVIEW

**Review by erwanriou — APPROVED** [review]

**Comment by grxy** [comment]
CC: @flotwig who approved the original dependency removal.

**Review by pedrohcavalcante — APPROVED** [review]

**Review by MichaelPhan — APPROVED** [review]

**Review by JanKanty — APPROVED** [review]

**Review by JJ — CHANGES_REQUESTED** [review]
I don't think it's a good idea to re-add deprecated code, even if it breaks installation in yarn. It breaks code that's not tested, so it's probably not needed anyway. This was part of the original request library, it's probably not needed now in cypress

> Probably not needed no matter what, since I haven't seen similar code in `axios` or others.

As an alternative, remove the require as well as the check that uses this. Tests are going to continue green, this is not going to be needed. Please refer to [this issue](https://github.com/ahmadnassri/node-har-validator/issues/173) in `har-validator` for the reasons why it was abandoned (mainly too much work due to `request`... which was also abandoned and eventually adopted here)

Other alternatives: import relevant code. However, I don't see HTTP archive validation as a real requirement in this context. See also #9 (which probably should have been closed by #14)

**Comment by erwanriou** [comment]
Just be aware that all cypress installations are stuck right now because of this and the temporary fiz to manually install this library not idealistic.

Yes its not great to reinstall a useless package, but it's even less to have the whole cypress installation flow down.

We can fix it here nor in cypress yarn package, please decide quickly.

**Review by paulusrex — APPROVED** [review]

**Review by derBinder — APPROVED** [review]

**Review by rmoralp — APPROVED** [review]

**Comment by JanKanty** [comment]
It's not only yarn problem. Npm without locks also fails miserably. I'd suggest revert this change and fix it by removing usage after.

**Review by larionov — APPROVED** [review]

**Review by mulsun — APPROVED** [review]

**Comment by damikun** [comment]
My CI/CD is broken since local dev has equal build pipeline I'm not able event build code locally now..  This is really big failure in repo..

**Comment by JJ** [comment]
> My CI/CD is broken since local dev has equal build pipeline I'm not able event build code locally now.. This is really big failure in repo..

As a temporal fix, you can install har-validator in the pipeline. This will fix it long-term, anyhow.

**Comment by meeroslav** [comment]
@JJ this trickles down to everyone who's solution contains cypress. 

The number of users is large and not everyone will find their way here (or cypress-io/cypress#19097) so fix needs to be published as soon as possible. Installing `har-validator` might not be such a simple task (think E2E tests on CI that generate the workspace and run install without lock files).

**Review by flotwig — APPROVED** [review]

**Comment by flotwig** [comment]
A PR to remove the usage of `har-validator` is welcome.

**Comment by JJ** [comment]
> A PR to remove the usage of `har-validator` is welcome.

Well, I can incorporate that into #16 if you want.

**Pull request merged**
