### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by stusmall**
## PR Checklist:
- [x] I have run `npm test` locally and all tests are passing.
- [x] I have added/updated tests for any new behavior.
       
- [x] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
       

## PR Description
The real point of this PR is to update some old dependencies and clear up vulnerabilities.  In service of this I did some clean up of key material that has been checked in and also rotated them.  Any changes to the code was trigger by the update of standard.  More details about specific changes can be found in each commit.

### CODE REVIEW

**Comment by stusmall** [comment]
One small detail. I never could get test-tunnel working locally even before changes.  It seems to be related to my local set up and not with the code.  It works in CI

**Comment by MikeMcC399** [comment]
@stusmall 

- Does this PR resolve issue https://github.com/cypress-io/request/issues/37?
- Are you testing against Node.js `18` and `20`? 
- GitHub Actions CI is using Node.js `18.16.0`. I believe this was out of necessity instead of using a later version such as the current LTS version Node.js `18.18.0` which was failing.
- CircleCI tests against Node.js `14`. That is no longer very meaningful because this version is in end-of-life since Apr 30, 2023

**Comment by stusmall** [comment]
@MikeMcC399 

The scope of my changes was just to update some dependencies to clear up, old known CVEs.  The goal isn't to try and tackle any other issues.  It doesn't resolve existing issues with node 20.  I have tested it with node 18.18.1 though and it passes.  [Here is an example of it passing on another branch where I was playing with a matrix with multiple versions](https://github.com/stusmall/request/actions/runs/6487476475/job/17617867570?pr=2).  I don't know what the issue causing pinning on 18.16.0 was but it doesn't look to be an issue with 18.18.1.

**Comment by MikeMcC399** [comment]
@stusmall 

Thanks for the feedback and explaining your goals. I cross-checked with Node.js `18.18.1` and the current version is now passing (without your PR changes).

There is something wrong with this PR now as GitHub is continuously showing "Processing updates". Maybe you need to force push it to reset it after your matrix tests?

**Comment by stusmall** [comment]
@MikeMcC399 The issue with being stuck should be fixed.  I had one more bit of clean up on the change to the github action workflow.  It should be working now.  [The test is passing on my fork](https://github.com/stusmall/request/actions/runs/6500783275) but you will need to approve the workflow to run for it run here.

**Comment by MikeMcC399** [comment]
@stusmall 

> The issue with being stuck should be fixed. I had one more bit of clean up on the change to the github action workflow. It should be working now. [The test is passing on my fork](https://github.com/stusmall/request/actions/runs/6500783275) but you will need to approve the workflow to run for it run here.

I'm a community Contributor, not a member of the Cypress team, and I don't have privileges to approve workflows or to merge PRs.

The next step would be for a member of the Cypress team to get involved with this PR. In [previous conversations](https://github.com/cypress-io/request/issues/35#issuecomment-1662125475) they have said they would like to move away from using this code and use `fetch` instead. Hopefully they will still want to use your contribution here.

**Comment by stusmall** [comment]
@MikeMcC399 Do you ever see cypress team interact with this repo anymore or is it abandoned?

**Comment by MikeMcC399** [comment]
@stusmall 

> Do you ever see cypress team interact with this repo anymore or is it abandoned?

The last time that the Cypress team was visibly active here was Sep 2, 2023. Only they can say what their plans are, however this repo is an essential dependency for Cypress.

I'm also waiting for feedback on 2 issues and 1 PR that I have submitted in this repo.

**Comment by stusmall** [comment]
It seems like this repo is abandoned

**Comment by jennifer-shehane** [comment]
We do use the repo for cypress, but if we were to put effort around this area, it would be to replace it honestly. Sorry for not being more responsive.

**Pull request closed without merging**
